spring.application.name=career-assessment-backend

server.port=${PORT:8080}

# =========================
# DATABASE
# =========================
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/careerdb}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:RKavya@2006}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# EMAIL OTP (HARDCODE TEST)
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=kavyarapolu999@gmail.com
spring.mail.password=ylxgwkbttyswjggx

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true